# Generated by Django 5.2.1 on 2025-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
